# syntax=docker/dockerfile:1.6
ARG ROS_DISTRO=humble
#Image de base ros2, multiplateforme (amd64, arm64)
FROM --platform=$TARGETPLATFORM ros:${ROS_DISTRO}-ros-base

ENV DEBIAN_FRONTEND=noninteractive

#Configuration du shell
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

#Installation de mavros, python
RUN apt-get update && apt-get install -y \
    ros-${ROS_DISTRO}-mavros \
    ros-${ROS_DISTRO}-mavros-extras \
    ros-${ROS_DISTRO}-mavlink \
    ros-${ROS_DISTRO}-rmw-cyclonedds-cpp \
    geographiclib-tools \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

#Script qui installe les datasets (dépendances) pour mavros
RUN /opt/ros/${ROS_DISTRO}/lib/mavros/install_geographiclib_datasets.sh

#librairies python
RUN pip3 install --no-cache-dir \
    numpy

#Dossier de référence du docker
WORKDIR /example_ws


#Autorisations et accès essentiels
ARG UID=1000
ARG GID=1000

RUN groupadd -g ${GID} dev \
    && useradd -m -u ${UID} -g ${GID} -s /bin/bash dev

RUN usermod -aG dialout dev

USER dev
